AMB2275_TANUJA SL

In [ ]:
import numpy as np
a=np.array([0,1,2,3])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
print(a.itemsize)
print(a.nbytes)
print(a.ndim)


[0 1 2 3]
<class 'numpy.ndarray'>
int64
(4,)
8
32
1


In [ ]:
a=([1,2,3,4],[5,6,7,8])
import numpy as np
print(np.__version__)


2.0.2


In [ ]:
#create an array with 5 dimensions
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("number of dimension",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimension 5


In [ ]:
#array indexing
# to get the 1st element from the following array
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])


1


In [ ]:
#write a program to calculate the sum of 3rd and 4th element number(1,2,3,4)
import numpy as np
a=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
#create 2D array 2x5 access the 2nd element on 1st dimension [2nd colum,1strow]
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element of 1stdimension:",a[0,1])

2nd element of 1stdimension: 2


In [ ]:
#acess the 3rd element of the 2nd array of the 1st array
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(a[0,1,0])

4


In [ ]:
#python program to perform basic arithmetic operation using  1D array
import numpy as np
a=np.array([1,2,3,4])
sum=a[0]+a[2]
diff=a[3]-a[2]
product=a[1]*a[2]
div=a[1]/a[2]
print("sum :",sum)
print("difference:",diff)
print("product:",product)
print("division",div)

sum : 4
difference: 1
product: 6
division 0.6666666666666666


In [ ]:
#slicing 1D array
import numpy as np
a=np.array([1,2,3,4,5,6,7])
print(a[1:5])
print(a[4:])
print(a[:4])
print(a[-3:-1])
print(a[:-1])
print(a[1:5:2])
print(a[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[1 2 3 4 5 6]
[2 4]
[1 3 5 7]


In [ ]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(a[0,1:4])
print(a[0,2])
print(a[0,1:4])
print(a[0,2:3,1:2])

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[7 8 9]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[8]]


In [ ]:
in advance happy birthday tanuja sl from anemadagu and entire c section  and from bio agents department


In [ ]:
#convert the following 1D array with 12 elements into a 3D
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(a)
print(a.reshape(3,2,2))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
arr=np.array([1,2,3,3,5])
x=arr.copy()
arr[2]=20
print(arr)
print(x)

[ 1  2 20  3  5]
[1 2 3 3 5]


In [ ]:
#numpy arrange function
import numpy as np
arr=np.array([1,2,3,4,5])
np.arange(1,5)



array([1, 2, 3, 4])

In [ ]:
#element arithmetic operation
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1@arr2)
print(arr1**arr2)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[    1    64]
 [ 2187 65536]]


In [ ]:
concatenated_arr=np.concatenate((arr1,arr2),axis=0)# concatenate along rows
concatenated_arr=np.concatenate((arr1,arr2),axis=1)# concatenate along columns
print(concatenated_arr)


[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
transposed_arr=arr1.transpose()
print(transposed_arr)
#rows elents to coloum
flattened_arr=arr1.flatten()
print(flattened_arr)
#multidimensional to single dimension

[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
import numpy as np
a=np.array([1+1j,1+0j,4.5+3,2,2j])
print("original array")
print(a)
print("checking for real numbers:")
print(np.isreal(a))
print("checking for complex numbers:")
print(np.iscomplex(a))
print("checking for scalar numbers:")
print(np.isscalar(a))
print("checking for scalar numbers:")
print(np.isscalar(3.1))


original array
[1. +1.j 1. +0.j 7.5+0.j 2. +0.j 0. +2.j]
checking for real numbers:
[False  True  True  True False]
checking for complex numbers:
[ True False False False  True]
checking for scalar numbers:
False
checking for scalar numbers:
True


In [ ]:
import numpy as np
crop_yield=np.array([
    [12,13,14,15,16],
    [11.2,12.2,11.3,12,14],
    [13,16,2,3,4],
    [8.9,3,5,5.6,8.4]
 ])
print('crop yield array(tons):')
print(crop_yield)
print(f'\nshape:{crop_yield}')
print(f'data type:{crop_yield.shape}')
print(f'total elements:{crop_yield.size}')

print(f'number of dimensions:{crop_yield.ndim}')


crop yield array(tons):
[[12.  13.  14.  15.  16. ]
 [11.2 12.2 11.3 12.  14. ]
 [13.  16.   2.   3.   4. ]
 [ 8.9  3.   5.   5.6  8.4]]

shape:[[12.  13.  14.  15.  16. ]
 [11.2 12.2 11.3 12.  14. ]
 [13.  16.   2.   3.   4. ]
 [ 8.9  3.   5.   5.6  8.4]]
data type:(4, 5)
total elements:20
number of dimensions:2


In [ ]:
import numpy as np
total_yield=np.sum(crop_yield)
avg_yld=np.mean(crop_yield,axis=1)
avg_yld_perseason=np.mean(crop_yield,axis=0)
maxyld=np.max(crop_yield)
minyld=np.min(crop_yield)



print(f'total yield:{total_yield}')
print(f'average yield:{avg_yld}')
print(f'average yield per season:{avg_yld_perseason}')
print(f'maximum yield:{maxyld}')
print(f'minimum yield:{minyld}')


total yield:199.60000000000002
average yield:[14.   12.14  7.6   6.18]
average yield per season:[11.275 11.05   8.075  8.9   10.6  ]
maximum yield:16.0
minimum yield:2.0


In [ ]:
#find best performing farm
best_farm=np.argmax(avg_yld)
worst_farm=np.argmin(avg_yld)
#arg max()does not return the max value itself it also gives value where it i slocated
print('\nbest performing farm:',best_farm+1)
print(f'their avg yield:{avg_yld[best_farm]}')
print('\nworst performing farm:',worst_farm+1)


best performing farm: 1
their avg yield:14.0

worst performing farm: 4


In [ ]:
#boolean indexing :find exceptional yields
exceptional_yields=crop_yield[crop_yield>13]
print(exceptional_yields)
print(f'exceptional yields:{exceptional_yields}')

[14. 15. 16. 14. 16.]
exceptional yields:[14. 15. 16. 14. 16.]


In [ ]:
#conditional operators:classify yields
categories=np.where(crop_yield>13,'high','low')
print(f'farm categories:\n{categories}')

farm categories:
[['low' 'low' 'high' 'high' 'high']
 ['low' 'low' 'low' 'low' 'high']
 ['low' 'high' 'low' 'low' 'low']
 ['low' 'low' 'low' 'low' 'low']]
